// <auto-generated />
using System;
using CatalogoDeMusicas.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CatalogoDeMusicas.Migrations
{
    [DbContext(typeof(TabelaBd))]
    partial class TabelaBdModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CatalogoDeMusicas.Models.cadastro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    b.Property<DateOnly>("DataCadastro")
                        .HasColumnType("date")
                        .HasColumnName("DataCadastro");

                    b.Property<DateOnly>("DataLancamento")
                        .HasColumnType("date")
                        .HasColumnName("DataLancamento");

                    b.Property<string>("NomeArtista")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("NomeArtista");

                    b.Property<string>("NomeGenero")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("NomeGenero");

                    b.Property<string>("Preco")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Preco");

                    b.Property<string>("TituloAlbum")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("TituloAlbum");

                    b.HasKey("Id");

                    b.ToTable("CatalogoDeMusicas");
                });
#pragma warning restore 612, 618
        }
    }
}
